name: project_pdd
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.3
  tflite_flutter: ^0.11.0
  image_picker: ^1.1.2
  image: ^4.5.4
  file_utils: ^1.0.1
  google_fonts: ^6.2.1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  mongo_dart: ^0.10.4
  bcrypt: ^1.1.3
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  http: ^1.4.0
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/my_model/
    - assets/.env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/BIRUROKH_ICON_PNG_Round.png"
